import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch

def draw_title_block(c, title, sheet_num, total_sheets):
    width, height = landscape(letter)
    # Border
    c.setLineWidth(1)
    c.rect(0.5*inch, 0.5*inch, width - 1*inch, height - 1*inch)
    
    # Title block bottom right
    tb_width = 3.5 * inch
    tb_height = 1.2 * inch
    x = width - 0.5*inch - tb_width
    y = 0.5*inch
    c.rect(x, y, tb_width, tb_height)
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x + 0.1*inch, y + tb_height - 0.2*inch, "Project: Z Spray Carrier")
    c.setFont("Helvetica", 10)
    c.drawString(x + 0.1*inch, y + tb_height - 0.4*inch, f"Drawing: {title}")
    c.drawString(x + 0.1*inch, y + tb_height - 0.6*inch, f"Sheet {sheet_num} of {total_sheets}")
    c.drawString(x + 0.1*inch, y + tb_height - 0.8*inch, "Revision: 0")
    c.drawString(x + 0.1*inch, y + tb_height - 1.0*inch, "Units: INCHES | Scale: NTS")
    c.drawString(x + 1.8*inch, y + tb_height - 1.0*inch, "Generated by: Z Spray Carrier Fabricator")

def fraction_str(val: float) -> str:
    # simple sixteenth rounding
    sixteenths = round(val * 16)
    if sixteenths == 0: return "0"
    whole = sixteenths // 16
    rem = sixteenths % 16
    if rem == 0: return str(whole)
    
    # simplify fraction
    if rem % 8 == 0:
        frac = f"{rem//8}/2"
    elif rem % 4 == 0:
        frac = f"{rem//4}/4"
    elif rem % 2 == 0:
        frac = f"{rem//2}/8"
    else:
        frac = f"{rem}/16"
        
    if whole > 0:
        return f"{whole} {frac}"
    return frac

def generate_shop_drawings(params, parts, output_path):
    c = canvas.Canvas(output_path, pagesize=landscape(letter))
    width, height = landscape(letter)
    
    # Sheet 1: General Arrangement
    draw_title_block(c, "GENERAL ARRANGEMENT", 1, 2)
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 1*inch, "PLAN VIEW")
    # Draw simple rect for carrier
    c_width = params.carrier_deck_length
    c_height = params.carrier_width
    
    # scale for drawing
    scale = 0.1 * inch
    center_x = width / 2
    center_y = height / 2 + 1*inch
    
    c.rect(center_x - (c_width/2)*scale, center_y - (c_height/2)*scale, c_width*scale, c_height*scale)
    c.drawString(center_x, center_y, f"Deck: {fraction_str(c_width)} x {fraction_str(c_height)}")
    c.showPage()
    
    # Sheet 2: Main Carrier
    draw_title_block(c, "MAIN CARRIER WELDMENT", 2, 2)
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, height - 1*inch, "MAIN CARRIER WELDMENT")
    
    y_offset = height - 1.5*inch
    for p in parts:
        c.drawString(1*inch, y_offset, f"{p['mark']} - {p['description']} - Qty {p['quantity']} - Length: {fraction_str(p['cut_length'])}")
        y_offset -= 0.2*inch
        
    c.showPage()
    c.save()
